SWENG894/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SWENG894.Data.Repository.IRepository;
using SWENG894.DataGenerationUtility;
using SWENG894.Models;
using SWENG894.Utility;
using SWENG894.Ranking;

namespace SWENG894.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly int _pageSize;
        private readonly ITestDataGenerator _testGenerator;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork, ITestDataGenerator testGeneratot)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _pageSize = 10;
            _testGenerator = testGeneratot;
        }

        public async Task<IActionResult> Index(string sort, string search, string filter, string list, string currentList, int? page)
        {
            ViewData["CurrentSort"] = sort;
            ViewData["SortOrder"] = String.IsNullOrEmpty(sort) ? "desc" : "";
            if (list == null)
            {
                list = currentList;
            }
            ViewData["CurrentList"] = list;

            if (search == null)
            {
                search = filter;
            }
            else
            {
                search = search.ToLower();
            }

            ViewData["CurrentFilter"] = search;

            //var matchingUsers = _unitOfWork.FriendRequest.GetUserFriends(sort, search, User.FindFirstValue(ClaimTypes.NameIdentifier), !string.IsNullOrEmpty(list)).ToList();
            // var personList = await PaginatedList<ApplicationUser>.Create(matchingUsers, page ?? 1, _pageSize);

            var ranking = _unitOfWork.Ranking.GetRankings();
            if (ranking != null)
            {
                var timeString = "Rankings generated on " + ranking.Timestamp + " UTC";
                ViewData["Timestamp"] = timeString;
            }
            else
            {
                ViewData["Timestamp"] = "";
            }

            return View(ranking);
        }

        public async Task<IActionResult> GenerateTestData()
        {
            _testGenerator.GenerateTestData();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveTestData()
        {
            _testGenerator.RemoveTestData();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GenerateRanks()
        {
            var ratings = _unitOfWork.ApplicationUser.GetAllUserRatings();
            var rankSys = new RankingSystem();
            var rankCenters = rankSys.GenerateRankings(5, ratings, 1000);

            var ranking = _unitOfWork.Ranking.GetRankings();
            if (ranking != null)
            {
                ranking.BronzeValue = rankCenters[0];
                ranking.SilverValue = rankCenters[1];
                ranking.GoldValue = rankCenters[2];
                ranking.PlatinumValue = rankCenters[3];
                ranking.DiamondValue = rankCenters[4];
                ranking.Timestamp = DateTime.UtcNow.ToString();

                _unitOfWork.Ranking.UpdateAsync(ranking);
                await _unitOfWork.Save();
            }
            else
            {
                var newRanking = new Models.Ranking()
                {
                    BronzeValue = rankCenters[0],
                    SilverValue = rankCenters[1],
                    GoldValue = rankCenters[2],
                    PlatinumValue = rankCenters[3],
                    DiamondValue = rankCenters[4],
                    Timestamp = DateTime.UtcNow.ToString()
                };

                await _unitOfWork.Ranking.AddAsync(newRanking);
                await _unitOfWork.Save();
            }

            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SWENG894/Areas/User/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SWENG894.Data.Repository.IRepository;
using SWENG894.Models;
using SWENG894.Utility;

namespace SWENG894.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "Admin, User")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly int _pageSize;

        [ExcludeFromCodeCoverage]
        public HomeController(IUnitOfWork unitOfWork, ILogger<HomeController> logger)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _pageSize = 100;
        }

        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> Index()
        {
            var feed = await PaginatedList<NewsFeed>.Create(_unitOfWork.NewsFeed.GetUserFeed(User.FindFirstValue(ClaimTypes.NameIdentifier)).ToList(), 1, _pageSize);
            return View(feed);
        }

        [ExcludeFromCodeCoverage]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [ExcludeFromCodeCoverage]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SWENG894/Areas/User/Controllers/WorkoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using SWENG894.Models;
using SWENG894.Utility;
using SWENG894.Data.Repository.IRepository;
using System.Diagnostics.CodeAnalysis;
using System.Security.Claims;

namespace SWENG894.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "Admin, User")]
    public class WorkoutsController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly IUnitOfWork _unitOfWork;
        private readonly int _pageSize;

        public WorkoutsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _pageSize = 5;
        }

        // GET: User/Workouts
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> Index(string sort, string search, string filter, string list, string currentList, int? page)
        {
            ViewData["CurrentSort"] = sort;
            ViewData["SortOrder"] = String.IsNullOrEmpty(sort) ? "desc" : "";

            if (list == null)
            {
                list = currentList;
            }
            ViewData["CurrentList"] = list;

            if (search == null)
            {
                search = filter;
            }
            else
            {
                search = search.ToLower();
            }

            ViewData["CurrentFilter"] = search;

            var workouts = _unitOfWork.Workout.GetUserWorkouts(sort, search, User.FindFirstValue(ClaimTypes.NameIdentifier), string.IsNullOrEmpty(list));
            if(workouts != null)
            {
                var workoutList = await PaginatedList<Workout>.Create(workouts.ToList(), page ?? 1, _pageSize);
                return View(workoutList);
            }

            var emptyList = await PaginatedList<Workout>.Create(new List<Workout>(), page ?? 1, _pageSize);
            return View(emptyList);

        }

        // GET: User/Workouts/Find
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> Find(string sort, string search, string filter, int? page, int? fave)
        {
            if(fave != null)
            {
                var favorite = await _unitOfWork.WorkoutFavorite.GetFirstOrDefaultAsync(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier) && x.WorkoutId == fave);

                if(favorite != null)
                {
                    await _unitOfWork.WorkoutFavorite.RemoveAsync(favorite);
                }
                else
                {
                    var user = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(x => x.Id == User.FindFirstValue(ClaimTypes.NameIdentifier));
                    var workout = await _unitOfWork.Workout.GetFirstOrDefaultAsync(x => x.Id == fave);

                    if(user != null && workout != null)
                    {
                        var newFave = new WorkoutFavorite
                        {
                            User = user,
                            Workout = workout
                        };
                        await _unitOfWork.WorkoutFavorite.AddAsync(newFave);
                    }                   
                }
                await _unitOfWork.Save();
            }

            ViewData["CurrentSort"] = sort;
            ViewData["SortOrder"] = String.IsNullOrEmpty(sort) ? "desc" : "";

            if (search == null)
            {
                search = filter;
            }
            else
            {
                search = search.ToLower();
            }

            ViewData["CurrentFilter"] = search;

            var resultList = await PaginatedList<Workout>.Create(_unitOfWork.Workout.FindNewWorkouts(sort, search, User.FindFirstValue(ClaimTypes.NameIdentifier)).ToList(), page ?? 1, _pageSize);

            return View(resultList);
        }

        // GET: User/Workouts/Details/5
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> Details(int? id, string fave, int? ex, string s)
        {
            if (id == null)
            {
                //count the number of records
                int total = _unitOfWork.Workout.GetAllAsync(x => x.Published).Result.Count();

                //select a random number from the count, that becomes the "id"
                var random = new Random();
                int num = random.Next(1, total);
                
                //search for the details of the randomly selected 
                var randomWorkout = await _unitOfWork.Workout.GetFirstOrDefaultAsync(m => m.Id == num, includeProperties: "Exercises");

                //because records may be deleted over time, id numbers will be deleted as well. So, loop through the list for an existing record
                while (randomWorkout == null)
                {
                    num = random.Next(1, total);
                    randomWorkout = await _unitOfWork.Workout.GetFirstOrDefaultAsync(m => m.Id == num, includeProperties: "Exercises");
                }

                var fave1 = await _unitOfWork.WorkoutFavorite.GetFirstOrDefaultAsync(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier) && x.WorkoutId == randomWorkout.Id);
                randomWorkout.IsFavorite = fave1 != null;

                if(!string.IsNullOrEmpty(fave))
                {
                    if(randomWorkout.IsFavorite)
                    {
                        await _unitOfWork.WorkoutFavorite.RemoveAsync(fave1);
                    }
                    else
                    {
                        var newFave = new WorkoutFavorite() 
                        {
                            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                            WorkoutId = randomWorkout.Id
                        };
                        await _unitOfWork.WorkoutFavorite.AddAsync(newFave);
                    }
                    randomWorkout.IsFavorite = !randomWorkout.IsFavorite;
                    await _unitOfWork.Save();
                }

                //return test results
                return View(randomWorkout);

            }

            var workout = await _unitOfWork.Workout.GetFirstOrDefaultAsync(m => m.Id == id, includeProperties: "Exercises");

            if (workout == null)
            {
                return NotFound();
            }

            workout.Exercises = workout.Exercises.OrderBy(x => x.Order).ToList();

            if (ex != null)
            {
                var exToReorder = await _unitOfWork.Exercise.GetFirstOrDefaultAsync(m => m.Id == ex);

                if (exToReorder != null && workout.Exercises.Contains(exToReorder))
                {
                    var exOrder = exToReorder.Order;
                    if (string.IsNullOrEmpty(s))
                    {
                        var exIndex = workout.Exercises.IndexOf(exToReorder);
                        if (exIndex > 0)
                        {
                            workout.Exercises.ElementAt(exIndex).Order = workout.Exercises.ElementAt(exIndex - 1).Order;
                            workout.Exercises.ElementAt(exIndex - 1).Order = exOrder;
                            _unitOfWork.Workout.UpdateAsync(workout);
                        }                                           
                    }
                    else
                    {
                        var exIndex = workout.Exercises.IndexOf(exToReorder);
                        if (exIndex <= workout.Exercises.Count - 2)
                        {
                            workout.Exercises.ElementAt(exIndex).Order = workout.Exercises.ElementAt(exIndex + 1).Order;
                            workout.Exercises.ElementAt(exIndex + 1).Order = exOrder;
                            _unitOfWork.Workout.UpdateAsync(workout);
                        }
                    }
                    await _unitOfWork.Save();
                }
                workout.Exercises = workout.Exercises.OrderBy(x => x.Order).ToList();
            }

            var fave2 = await _unitOfWork.WorkoutFavorite.GetFirstOrDefaultAsync(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier) && x.WorkoutId == workout.Id);
            workout.IsFavorite = fave2 != null;

            if (!string.IsNullOrEmpty(fave))
            {
                if (workout.IsFavorite)
                {
                    await _unitOfWork.WorkoutFavorite.RemoveAsync(fave2);                    
                }
                else
                {
                    var newFave = new WorkoutFavorite()
                    {
                        UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                        WorkoutId = workout.Id
                    };
                    await _unitOfWork.WorkoutFavorite.AddAsync(newFave);
                }
                workout.IsFavorite = !workout.IsFavorite;
                await _unitOfWork.Save();
            }

            

            return View(workout);
        }

        // GET: User/Workouts/Create
        [ExcludeFromCodeCoverage]
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Workouts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Workout workout, int seconds = 0)
        {
            //time is in minutes, store in seconds. Could be broken up and written as unit test
            if(seconds == 0)
            {
                seconds = 0;
            }
            
            if(workout.ScoringType == Workout.Scoring.Time)
            {
                workout.Time = workout.Time * 60 + seconds;

SWENG894/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SWENG894.Models;

namespace SWENG894.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SWENG894/Areas/User/Views/Home/Index.cshtml
@model SWENG894.Utility.PaginatedList<SWENG894.Models.NewsFeed>

@if (Model.Count > 0)
{
    foreach (var feed in Model)
    {
        switch (feed.FeedType)
        {
            case NewsFeed.FeedTypes.AcceptedChallenge:
                if (feed.RelatedUserId == User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value)
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@feed.User.FullName @(" accepted your challenge!")</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@feed.User.FullName @(" accepted a challenge from ") @feed.RelatedUser.FullName@("!")</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                        </div>
                    </div>
                }
                break;

            case NewsFeed.FeedTypes.CompletedChallenge:
                if (feed.RelatedUserId == User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value)
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@feed.User.FullName @(" completed your challenge!")</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Challenges" asp-action="Details" asp-route-id="@feed.RelatedChallengeId" class="btn btn-primary">View Challenge</a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@feed.User.FullName @(" completed a challenge from ") @feed.RelatedUser.FullName@("!")</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                        </div>
                    </div>
                }
                break;

            case NewsFeed.FeedTypes.CompletedWorkout:
                <div class="card mb-2">
                    <h5 class="card-header">@feed.User.FullName @(" completed a workout!")</h5>
                    <div class="card-body">
                        <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                        <p class="card-text">@feed.RelatedWorkout.Notes</p>
                        <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                    </div>
                </div>
                break;

            case NewsFeed.FeedTypes.PublishedWorkout:
                <div class="card mb-2">
                    <h5 class="card-header">@feed.User.FullName @(" published a new workout.")</h5>
                    <div class="card-body">
                        <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                        <p class="card-text">@feed.RelatedWorkout.Notes</p>
                        <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                    </div>
                </div>
                break;

            case NewsFeed.FeedTypes.SentChallenge:
                if (feed.RelatedUserId == User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value)
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@("You have been challenged by ") @feed.User.FullName@("!")</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Challenges" asp-action="Details" asp-route-id="@feed.RelatedChallengeId" class="btn btn-primary">View Challenge</a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@feed.User.FullName @(" challeneged ") @feed.RelatedUser.FullName</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                        </div>
                    </div>
                }
                break;

            case NewsFeed.FeedTypes.SharedWorkout:
                if (feed.RelatedUserId == User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value)
                {
                    <div class="card mb-2">
                        <h5 class="card-header">@feed.User.FullName @(" shared a workout with you!")</h5>
                        <div class="card-body">
                            <h5 class="card-title">@feed.RelatedWorkout.Name</h5>
                            <p class="card-text">@feed.RelatedWorkout.Notes</p>
                            <a asp-area="User" asp-controller="Workouts" asp-action="Details" asp-route-id="@feed.RelatedWorkoutId" class="btn btn-primary">View Workout</a>
                        </div>
                    </div>
                }
                break;
        }
    }
}
else
{
    <div class="card mb-2">
        <h5 class="card-header">No news to show.</h5>
        <div class="card-body">
            <p class="card-text">Add more friends to see additonal feeds.</p>
        </div>
    </div>
}