SWENG894/Models/Ranking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWENG894.Models
{
    public class Ranking
    {
        public int Id { get; set; }
        public int BronzeValue { get; set; }
        public int SilverValue { get; set; }
        public int GoldValue { get; set; }
        public int PlatinumValue { get; set; }
        public int DiamondValue { get; set; }
        public string Timestamp { get; set; }
    }
}

SWENG894/Areas/User/Controllers/FriendsController.cs
using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SWENG894.Data;
using SWENG894.Data.Repository.IRepository;
using SWENG894.Models;
using SWENG894.Utility;
using SWENG894.ViewModels;
using static SWENG894.Models.FriendRequest;

namespace SWENG894.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "Admin, User")]
    public class FriendsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly int _pageSize;

        public FriendsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _pageSize = 5;
        }

        // GET: User/Friends
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> Index(string sort, string search, string filter, string list, string currentList, int? page)
        {
            ViewData["CurrentSort"] = sort;
            ViewData["SortOrder"] = String.IsNullOrEmpty(sort) ? "desc" : "";

            if(list == null)
            {
                list = currentList;
            }
            ViewData["CurrentList"] = list;

            if (search == null)
            {
                search = filter;
            }
            else
            {
                search = search.ToLower();
            }

            ViewData["CurrentFilter"] = search;

            var matchingUsers = _unitOfWork.FriendRequest.GetUserFriends(sort, search, User.FindFirstValue(ClaimTypes.NameIdentifier), !string.IsNullOrEmpty(list)).ToList();
            var personList = await PaginatedList<ApplicationUser>.Create(matchingUsers, page ?? 1, _pageSize);

            return View(personList);
        }

        // GET: User/Friends/Find
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> Find(string sort, string search, string filter, int? page)
        {
            ViewData["CurrentSort"] = sort;
            ViewData["SortOrder"] = String.IsNullOrEmpty(sort) ? "desc" : "";

            if (search == null)
            {
                search = filter;
            }
            else
            {
                search = search.ToLower();
            }

            ViewData["CurrentFilter"] = search;

            var resultList = await PaginatedList<ApplicationUser>.Create(_unitOfWork.FriendRequest.FindNewFriends(sort, search, User.FindFirstValue(ClaimTypes.NameIdentifier)).ToList(), page ?? 1, _pageSize);

            return View(resultList);
        }

        // GET: User/Friends/SendRequest/5
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> SendRequest(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personToFriend = await _unitOfWork.FriendRequest.GetPersonToFriend(id);

            if (personToFriend == null)
            {
                return NotFound();
            }

            return View(personToFriend);
        }

        // POST: User/Friends/SendRequest
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("SendRequest")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendRequestPost(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userToFriend = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(u => u.Id == id);

            if (userToFriend == null || User.FindFirstValue(ClaimTypes.NameIdentifier) == null)
            {
                return NotFound();
            }

            var friendRequest = await _unitOfWork.FriendRequest
                .GetFirstOrDefaultAsync(m => m.RequestedById == User.FindFirstValue(ClaimTypes.NameIdentifier) && m.RequestedForId == id);

            if (friendRequest == null)
            {
                FriendRequest request = new FriendRequest
                {
                    RequestedById = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    RequestedForId = userToFriend.Id,
                    RequestTime = DateTime.Now,
                    RequestStatus = FriendRequestStatus.New,
                    ReceiverStatus = FriendRequestStatus.New,
                    RequesterStatus = FriendRequestStatus.Approved
                };
                await _unitOfWork.FriendRequest.AddAsync(request);


                Message msg = new Message()
                {
                    SentById = request.RequestedById,
                    SentToId = request.RequestedForId,
                    Subject = "New friend request.",
                    Body = "Someone wants to be friends with you.",
                    SentTime = DateTime.Now,
                    MessageType = Message.MessageTypes.FriendRequest,
                    SendStatus = Message.MessageSendStatud.New,
                    ReadStatus = Message.MessageReadStatud.New,
                    DeletedByReceiver = false,
                    DeletedBySender = false
                };
                await _unitOfWork.Message.AddAsync(msg);

                await _unitOfWork.Save();
                return View(userToFriend);
            }

            return View(userToFriend);
            //return RedirectToAction(nameof(Index));
        }

        // GET: User/Friends/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var friendRequest = await _unitOfWork.FriendRequest
                .GetFirstOrDefaultAsync(m => m.RequestedById == id,
                includeProperties: "RequestedBy,RequestedFor");

            if (friendRequest == null)
            {
                return NotFound();
            }

            return View(friendRequest);
        }

        // GET: User/Friends/ViewRequest/5
        public async Task<IActionResult> ViewRequest(string sender, string receiver)
        {
            if (sender == null || receiver == null)
            {
                return NotFound();
            }

            var friendRequest = await _unitOfWork.FriendRequest
                .GetFirstOrDefaultAsync(m => m.RequestedById == sender && m.RequestedForId == receiver || m.RequestedById == receiver && m.RequestedForId == sender,
                includeProperties: "RequestedBy,RequestedFor");

            if (friendRequest == null || (friendRequest.RequestedForId != User.FindFirstValue(ClaimTypes.NameIdentifier) && friendRequest.RequestedById != User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return NotFound();
            }

            return View(friendRequest);
        }

        // POST: User/Friends/ViewRequest
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("ViewRequest")]
        [ValidateAntiForgeryToken]
        [ExcludeFromCodeCoverage]
        public async Task<IActionResult> ViewRequestPost(string sender, string receiver, FriendRequestStatus status)
        {
            var friendRequest = await _unitOfWork.FriendRequest
                .GetFirstOrDefaultAsync(m => m.RequestedById == sender && m.RequestedForId == receiver || m.RequestedById == receiver && m.RequestedForId == sender,
                includeProperties: "RequestedBy,RequestedFor");

            if (friendRequest == null || (friendRequest.RequestedForId != User.FindFirstValue(ClaimTypes.NameIdentifier) && friendRequest.RequestedById != User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return NotFound();
            }

            if(friendRequest.RequestedForId == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {          
                switch(friendRequest.RequestStatus)
                {
                    case FriendRequestStatus.New:
                        
                        if(status == FriendRequestStatus.Approved)
                        {
                            friendRequest.RequestStatus = FriendRequestStatus.Approved;
                            friendRequest.ReceiverStatus = FriendRequestStatus.Approved;
                            friendRequest.BecameFriendsTime = DateTime.Now;
                        }
                        else if (status == FriendRequestStatus.Rejected)
                        {
                            friendRequest.RequestStatus = FriendRequestStatus.Rejected;
                            friendRequest.ReceiverStatus = FriendRequestStatus.Rejected;
                        }
                        break;
                    case FriendRequestStatus.Approved:

                        if (status == FriendRequestStatus.Rejected)
                        {
                            friendRequest.RequestStatus = FriendRequestStatus.Rejected;
                            friendRequest.ReceiverStatus = FriendRequestStatus.Rejected;
                        }
                        else if(status == FriendRequestStatus.Approved)
                        {
                            friendRequest.RequestStatus = SetFriendRequestStatus(friendRequest.RequesterStatus, FriendRequestStatus.Approved);
                            friendRequest.ReceiverStatus = FriendRequestStatus.Approved;
                        }
                        break;
                    case FriendRequestStatus.Rejected:

                        if (status == FriendRequestStatus.Approved)
                        {

SWENG894/Areas/User/Views/Friends/Create.cshtml
@model SWENG894.Models.FriendRequest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FriendRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RequestedById" class="control-label"></label>
                <select asp-for="RequestedById" class ="form-control" asp-items="ViewBag.RequestedById"></select>
            </div>
            <div class="form-group">
                <label asp-for="RequestedForId" class="control-label"></label>
                <select asp-for="RequestedForId" class ="form-control" asp-items="ViewBag.RequestedForId"></select>
            </div>
            <div class="form-group">
                <label asp-for="RequestTime" class="control-label"></label>
                <input asp-for="RequestTime" class="form-control" />
                <span asp-validation-for="RequestTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BecameFriendsTime" class="control-label"></label>
                <input asp-for="BecameFriendsTime" class="form-control" />
                <span asp-validation-for="BecameFriendsTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestStatus" class="control-label"></label>
                <select asp-for="RequestStatus" class="form-control"></select>
                <span asp-validation-for="RequestStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SWENG894/Areas/User/Views/Friends/Delete.cshtml
@model SWENG894.Models.FriendRequest

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h4>
        @if (Model.RequestedForId == User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value)
        {
            @("Are you sure you want to remove ") @Model.RequestedBy.FullName @(" ?")
        }
        else
        {
            @("Are you sure you want to remove ") @Model.RequestedFor.FullName @(" ?")
        }
    </h4>
    <div class="btn-toolbar mb-2 mb-md-0">
        <form asp-action="Delete">
            <input type="hidden" asp-for="RequestedById" />
            <input type="hidden" asp-for="RequestedForId" />
            <a class="btn btn-secondary mr-2" asp-action="Index">Back to List</a>
            <input type="submit" class="btn btn-danger" value="Delete" />
        </form>
    </div>
</div>

SWENG894/Areas/User/Views/Friends/Details.cshtml
@model SWENG894.Models.FriendRequest

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FriendRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestedBy.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedFor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestedFor.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BecameFriendsTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BecameFriendsTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestStatus)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

SWENG894/Areas/User/Views/Friends/Edit.cshtml
@model SWENG894.Models.FriendRequest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FriendRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RequestedById" />
            <input type="hidden" asp-for="RequestedForId" />
            <div class="form-group">
                <label asp-for="RequestTime" class="control-label"></label>
                <input asp-for="RequestTime" class="form-control" />
                <span asp-validation-for="RequestTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BecameFriendsTime" class="control-label"></label>
                <input asp-for="BecameFriendsTime" class="form-control" />
                <span asp-validation-for="BecameFriendsTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestStatus" class="control-label"></label>
                <select asp-for="RequestStatus" class="form-control"></select>
                <span asp-validation-for="RequestStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SWENG894/Areas/User/Views/Friends/Find.cshtml
@model SWENG894.Utility.PaginatedList<SWENG894.Models.ApplicationUser>

    <h4>Find Friends</h4>

    <form asp-action="Find" method="get">
        <div class="btn-group mb-2" role="group" aria-label="InOut Box">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search" aria-label="Search" name="search" aria-describedby="button-find" value="@ViewBag.CurrentFilter">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-find">Search</button>
                </div>

            </div>
        </div>
        <a class="btn btn-secondary float-right" id="button-find" asp-action="Index">Cancel</a>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    <a asp-action="Find" asp-route-sort="@ViewBag.SortOrder" asp-route-filter="@ViewBag.CurrentFilter">Last Name</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        <a asp-action="Profile" asp-route-id="@item.Id"><i class="far fa-address-card" tool-tip-toggle="tooltip" data-original-title="User Profile"></i></a> @("|")
                        <a asp-action="SendRequest" asp-route-id="@item.Id"><i class="fas fa-user-friends" tool-tip-toggle="tooltip" data-original-title="Send Friend Request"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Find"
       asp-route-sort="@ViewBag.CurrentSort"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-search="@ViewBag.CurrentFilter"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Find"
       asp-route-sort="@ViewBag.CurrentSort"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-search="@ViewBag.CurrentFilter"
       class="btn btn-default @nextDisabled">
        Next
    </a>

SWENG894/Areas/User/Views/Friends/Index.cshtml
@model SWENG894.Utility.PaginatedList<SWENG894.Models.ApplicationUser>

<h4>Friends List</h4>

<form asp-action="Index" method="get">
    <div class="btn-group mb-2" role="group">

        <div class="input-group mb-3">
            <div class="btn-group btn-group-toggle mr-2" role="group">
                <a asp-action="Index" asp-route-list="" type="button" class="btn btn-outline-secondary" id="friends">Friends</a>
                <a asp-action="Index" asp-route-list="blocked" type="button" class="btn btn-outline-secondary" id="blocked">Blocked</a>
            </div>
            <input type="text" class="form-control" placeholder="Search" aria-label="Search" name="search" aria-describedby="button-find" value="@ViewBag.CurrentFilter">
            <input type="hidden" name="list" value="@ViewBag.CurrentList" />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-find">Search</button>
            </div>
        </div>
    </div>
    <a class="btn btn-primary float-right" id="button-find" asp-action="Find">Add Friends</a>
</form>

@if (Model.Count > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index" asp-route-sort="@ViewBag.SortOrder" asp-route-filter="@ViewBag.CurrentFilter" asp-route-list="@ViewBag.CurrentList">Name</a>
                </th>
                <th>
                    Options
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @if (ViewBag.CurrentList == null || ViewBag.CurrentList == "")
                        {
                            <a asp-area="User" asp-controller="Challenges" asp-action="Create" asp-route-id="@item.Id"><i class="fas fa-dumbbell" tool-tip-toggle="tooltip" data-original-title="Send Challenge"></i></a> @("|")
                            <a asp-area="User" asp-controller="Messages" asp-action="Create" asp-route-id="@item.Id" asp-route-origin="friends"><i class="far fa-comment-dots" tool-tip-toggle="tooltip" data-original-title="Send Message"></i></a> @("|")
                            <a asp-area="User" asp-controller="Friends" asp-action="Profile" asp-route-id="@item.Id"><i class="far fa-address-card" tool-tip-toggle="tooltip" data-original-title="User Profile"></i></a> @("|")
                        }
                        <a asp-action="ViewRequest" asp-route-sender="@User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value" asp-route-receiver="@item.Id"><i class="fas fa-tasks" tool-tip-toggle="tooltip" data-original-title="Manage Friend"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

    <a asp-action="Index"
       asp-route-sort="@ViewBag.CurrentSort"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-search="@ViewBag.CurrentFilter"
       asp-route-list="@ViewBag.CurrentList"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sort="@ViewBag.CurrentSort"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-search="@ViewBag.CurrentFilter"
       asp-route-list="@ViewBag.CurrentList"
       class="btn btn-default @nextDisabled">
        Next
    </a>
}
else
{
    <i class="far fa-surprise fa-3x"></i>
    <p>No friends found. Change your search parameter or add more friends.</p>
}

@section Scripts {
    <script>
        var tab = GetParameterByName("list");
        if (tab != null && tab != "") {
            $("#blocked").button('toggle');
        } else {
            $("#friends").button('toggle');
        }
    </script>
}

SWENG894/Areas/User/Views/Friends/Profile.cshtml
@model SWENG894.ViewModels.UserProfileViewModel

<div>
    <h4>Profile</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dd class="col-sm-2">
            <b>Rank</b>
        </dd>
        <dd class="col-sm-10">
            @if (ViewBag.Ranking == 0)
            {
                <span style="color: #b08d57"><i class="fas fa-medal fa-3x"></i></span>@("Bronze")
            }
            else if (ViewBag.Ranking == 1)
            {
                <span style="color: silver"><i class="fas fa-medal fa-3x"></i></span>@("Silver")
            }
            else if (ViewBag.Ranking == 2)
            {
                <span style="color: gold"><i class="fas fa-medal fa-3x"></i></span>@("Gold")
            }
            else if (ViewBag.Ranking == 3)
            {
                <span style="color: lightskyblue"><i class="fas fa-star fa-3x"></i></span>@("Platinum")
            }
            else if (ViewBag.Ranking == 4)
            {
                <span style="color: dodgerblue"><i class="fas fa-gem fa-3x"></i></span>@("Diamond")
            }
            else
            {
                @("Error Computing Rank")
            }
        </dd>
    </dl>
    <a asp-action="Rankings">What does this rank mean?</a>
</div>

SWENG894/Areas/User/Views/Friends/Rankings.cshtml
<div>
    <h4>Ranking Descriptions</h4>
    <hr />
    <table class="table table-striped" style="width: 50%;">
        <colgroup>
            <col span="1" style="width: 50%;" />
            <col span="1" style="width: 50%;" />
        </colgroup>
        <thead>
            <tr>
                <th>
                    Rank
                </th>
                <th>
                    Description
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <span style="color: dodgerblue"><i class="fas fa-gem fa-3x"></i></span>@("Diamond")
                </td>
                <td>
                    Diamond is the highest ranking given to the top group of players.
                </td>
            </tr>
            <tr>
                <td>
                    <span style="color: lightskyblue"><i class="fas fa-star fa-3x"></i></span>@("Platinum")
                </td>
                <td>
                    Platinum is the second highest ranking.
                </td>
            </tr>
            <tr>
                <td>
                    <span style="color: gold"><i class="fas fa-medal fa-3x"></i></span>@("Gold")
                </td>
                <td>
                    Gold is the middle ranking.
                </td>
            </tr>
            <tr>
                <td>
                    <span style="color: silver"><i class="fas fa-medal fa-3x"></i></span>@("Silver")
                </td>
                <td>
                    Silver is the second ranking.
                </td>
            </tr>
            <tr>
                <td>
                    <span style="color: #b08d57"><i class="fas fa-medal fa-3x"></i></span>@("Bronze")
                </td>
                <td>
                    Bronze is the first ranking, generally given to new competitors.
                </td>
            </tr>
        </tbody>
    </table>
    <a href="javascript:history.back()">Back</a>
</div>

SWENG894/Areas/User/Views/Friends/SendRequest.cshtml
@model SWENG894.Models.ApplicationUser

@if (Model.HasRequestFrom(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value))
{
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h4>
            Friend request sent!
        </h4>
        <div class="btn-toolbar mb-2 mb-md-0">
            <form asp-action="SendRequest">
                <input type="hidden" asp-for="Id" />
                <a class="btn btn-secondary mr-2" asp-action="Find">Back to List</a>
            </form>
        </div>
    </div>
}
else
{
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h4>
            Send a friend request to this person?
        </h4>
        <div class="btn-toolbar mb-2 mb-md-0">
            <form asp-action="SendRequest">
                <input type="hidden" asp-for="Id" />
                <a class="btn btn-secondary mr-2" asp-action="Find">Back to List</a>
                <input type="submit" class="btn btn-primary" value="Yes" />
            </form>
        </div>
    </div>

    <div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
        </dl>
    </div>
}