SWENG894/Models/Challenge.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SWENG894.Models
{
    public class Challenge
    {
        public int Id { get; set; }
        [Required]
        public string ChallengerId { get; set; }
        public ApplicationUser Challenger { get; set; }
        [Required]
        public string ContenderId { get; set; }
        public ApplicationUser Contender { get; set; }
        public int WorkoutId { get; set; }
        public Workout Workout { get; set; }
        public int? ChallengerResultId { get; set; }

        [Display(Name = "Challenger Result")]
        public WorkoutResult ChallengerResult { get; set; }
        public int? ContenderResultId { get; set; }

        [Display(Name = "Contender Result")]
        public WorkoutResult ContenderResult { get; set; }

        [Display(Name = "Challenge Status")]
        public ChallengeStatus ChallengeProgress { get; set; }
        [Required]
        public DateTime CreateDate { get; set; }

        public enum ChallengeStatus
        {
            New,
            Accepted,          
            CompletedByChallenger,
            CompletedByContender,
            Rejected,
            Completed,
            Canceled
        }
    }
}

SWENG894/ViewModels/ChallengeViewModel.cs
using SWENG894.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SWENG894.ViewModels
{
    public class ChallengeViewModel
    {
        public string ChallengerId { get; set; }
        public ApplicationUser Challenger { get; set; }

        [Display(Name = "Send To")]
        public string ContenderId { get; set; }
        public ApplicationUser Contender { get; set; }

        [Display(Name = "Workout")]
        public int WorkoutId { get; set; }
        public List<WorkoutFavorite> WorkoutFavorites { get; set; }
        public IEnumerable<ApplicationUser> Friends { get; set; }
    }
}

SWENG894/Areas/User/Controllers/ChallengesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Math.EC.Rfc7748;
using SWENG894.Data;
using SWENG894.Data.Repository;
using SWENG894.Data.Repository.IRepository;
using SWENG894.Models;
using SWENG894.Utility;
using SWENG894.ViewModels;
using static SWENG894.Models.Challenge;

namespace SWENG894.Areas.User.Controllers
{
    [Area("User")]
    public class ChallengesController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly IUnitOfWork _unitOfWork;
        private readonly int _pageSize;

        public ChallengesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _pageSize = 5;
        }

        [ExcludeFromCodeCoverage]
        // GET: User/Challenges
        public async Task<IActionResult> Index(string sort, string search, string filter, string list, string currentList, int? page)
        {
            ViewData["CurrentSort"] = sort;
            ViewData["SortOrder"] = String.IsNullOrEmpty(sort) ? "desc" : "";
            if (list == null)
            {
                list = currentList;
            }
            ViewData["CurrentList"] = list;

            if (search == null)
            {
                search = filter;
            }
            else
            {
                search = search.ToLower();
            }

            ViewData["CurrentFilter"] = search;

            var challenges = _unitOfWork.Challenge.GetUserChallenges(sort, search, User.FindFirstValue(ClaimTypes.NameIdentifier), !string.IsNullOrEmpty(list));
            var challengeList = await PaginatedList<Challenge>.Create(challenges.ToList(), page ?? 1, _pageSize);

            return View(challengeList);
        }

        // GET: User/Challenges/Details/5
        public async Task<IActionResult> Details(int? id, ChallengeStatus? status)
        {
            if (id == null)
            {
                return NotFound();
            }

            var challenge = await _unitOfWork.Challenge.GetFirstOrDefaultAsync(c => c.Id == id, includeProperties: "Challenger,ChallengerResult,Contender,ContenderResult,Workout");

            if (challenge == null)
            {
                return NotFound();
            }

            // Could be simplified. Not sure how this will function yet.
            if(status != null && status >= ChallengeStatus.New && status <= ChallengeStatus.Canceled)
            {
                if(challenge.ContenderId == User.FindFirstValue(ClaimTypes.NameIdentifier))
                {
                    switch(challenge.ChallengeProgress)
                    {
                        case ChallengeStatus.New:
                            if (status == ChallengeStatus.Accepted || status == ChallengeStatus.Rejected)
                            {
                                challenge.ChallengeProgress = (ChallengeStatus)status;
                                _unitOfWork.Challenge.UpdateAsync(challenge);
                                if(status == ChallengeStatus.Rejected)
                                {
                                    var news = await _unitOfWork.NewsFeed.GetFirstOrDefaultAsync(x => x.RelatedChallengeId == challenge.Id);
                                    if(news != null)
                                    {
                                        news.Dismissed = true;
                                        _unitOfWork.NewsFeed.Update(news);
                                    }                                   
                                }
                                if(status == ChallengeStatus.Accepted)
                                {
                                    var feed = new NewsFeed()
                                    {
                                        User = challenge.Challenger,
                                        RelatedUser = challenge.Contender,
                                        RelatedChallenge = challenge,
                                        RelatedWorkout = challenge.Workout,
                                        CreateDate = DateTime.Now,
                                        FeedType = NewsFeed.FeedTypes.AcceptedChallenge,
                                        Description = challenge.Contender.FullName + " accepted a challenge from " + challenge.Challenger.FullName,
                                        Dismissed = false
                                    };
                                    await _unitOfWork.NewsFeed.AddAsync(feed);
                                }
                                await _unitOfWork.Save();
                            }
                            break;
                    }
                }
            }

            return View(challenge);
        }

        [ExcludeFromCodeCoverage]
        // GET: User/Challenges/Create
        public async Task<IActionResult> Create(string id)
        {
            var challengerUser = await _unitOfWork.ApplicationUser.GetUserWithWorkouts(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var contenderUser = await _unitOfWork.ApplicationUser.GetAsync(id);
            
            //if(challengerUser == null || contenderUser == null)
            //{
            //    return NotFound();
            //}

            var challengerFriends = _unitOfWork.FriendRequest.GetUserFriends("", "", challengerUser.Id, false);
            if(challengerFriends.Where(x => x.Id == id) == null)
            {
                return NotFound();
            }

            var challenge = new ChallengeViewModel()
            {
                Challenger = challengerUser,
                Contender = contenderUser,
                Friends = challengerFriends,
                WorkoutFavorites = challengerUser.WorkoutFavorites.ToList()
            };
            return View(challenge);
        }

        // POST: User/Challenges/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ChallengeViewModel challenge)
        {
            if (ModelState.IsValid)
            {
                var challengerUser = await _unitOfWork.ApplicationUser.GetUserWithWorkouts(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var contenderUser = await _unitOfWork.ApplicationUser.GetAsync(challenge.ContenderId);

                if (challengerUser == null || contenderUser == null)
                {
                    return NotFound();
                }

                var challengerFriends = _unitOfWork.FriendRequest.GetUserFriends("", "", challengerUser.Id, false);
                if (challengerFriends.Where(x => x.Id == challenge.ContenderId) == null)
                {
                    return NotFound();
                }

                var selectedWorkout = await _unitOfWork.Workout.GetFirstOrDefaultAsync(x => x.Id == challenge.WorkoutId);
                if(selectedWorkout == null)
                {
                    return NotFound();
                }

                var newChallenge = new Challenge()
                {
                    Challenger = challengerUser,
                    Contender = contenderUser,
                    Workout = selectedWorkout,
                    ChallengeProgress = Models.Challenge.ChallengeStatus.New,
                    CreateDate = DateTime.Now
                };

                await _unitOfWork.Challenge.AddAsync(newChallenge);
                await _unitOfWork.Save();

                var msg = new Message()
                {
                    SentById = challengerUser.Id,
                    SentToId = contenderUser.Id,
                    Subject = "You've been challenged!",
                    Body = challengerUser.FullName + " sent you a challenge!",
                    SentTime = DateTime.Now,
                    MessageType = Message.MessageTypes.Challenge,
                    SendStatus = Message.MessageSendStatud.New,
                    ReadStatus = Message.MessageReadStatud.New,
                    DeletedByReceiver = false,
                    DeletedBySender = false
                };

                var feed = new NewsFeed()
                {
                    User = challengerUser,
                    RelatedUser = contenderUser,
                    RelatedChallenge = newChallenge,
                    RelatedWorkout = selectedWorkout,
                    CreateDate = DateTime.Now,
                    FeedType = NewsFeed.FeedTypes.SentChallenge,
                    Description = challengerUser.FullName + " sent a challenge to " + contenderUser.FullName,
                    Dismissed = false
                };

                await _unitOfWork.Message.AddAsync(msg);
                await _unitOfWork.NewsFeed.AddAsync(feed);
                await _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(challenge);
        }

        [ExcludeFromCodeCoverage]
        private bool ChallengeExists(int id)
        {
            return _unitOfWork.Challenge.ObjectExists(id);
        }
    }
}

SWENG894/Areas/User/Views/Challenges/Create.cshtml
@model SWENG894.ViewModels.ChallengeViewModel

<form asp-action="Create">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h4>
            Send Challenge
        </h4>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a class="btn btn-secondary mr-2" asp-area="User" asp-controller="Friends" asp-action="Index">Cancel</a>
            @if (Model.Friends.Count() > 0 && Model.WorkoutFavorites.Count > 0)
            {
                <input type="submit" value="Send" class="btn btn-primary" />
            }
        </div>
    </div>

    @if (Model.Friends.Count() > 0)
    {
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="@Model.ContenderId" class="control-label"></label>
            @Html.DropDownListFor(p => p.ContenderId, new SelectList(Model.Friends, "Id", "FullName"), new { @class = "form-control" })
        </div>
    }
    else
    {
        <i class="far fa-sad-tear fa-3x"></i>
        <p>You don't have any friends to challenge.</p>
        <a class="btn btn-primary" asp-area="User" asp-controller="Friends" asp-action="Find">Add Friends</a>
    }

    @if (Model.WorkoutFavorites.Count > 0)
    {
        <div class="form-group">
            <label asp-for="@Model.WorkoutId" class="control-label"></label>
            @Html.DropDownListFor(p => p.WorkoutId, new SelectList(Model.WorkoutFavorites, "Workout.Id", "Workout.Name"), new { @class = "form-control" })
        </div>
    }
    else
    {
        <i class="far fa-sad-tear fa-3x"></i>
        <p>You don't have any saved workouts.</p>
        <a class="btn btn-primary" asp-area="User" asp-controller="Workouts" asp-action="Index">Find Workouts</a>
    }
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SWENG894/Areas/User/Views/Challenges/Details.cshtml
@model SWENG894.Models.Challenge

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h4>
        Challenge Details
    </h4>
    <div>
        <form asp-action="Details">
            @if (Model.Contender.Id == User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value)
            {
                switch (Model.ChallengeProgress)
                {
                    case Challenge.ChallengeStatus.New:

                        <input asp-action="Details" asp-route-id="@Model.Id" asp-route-status="@Challenge.ChallengeStatus.Accepted" type="submit" value="Accept" class="btn btn-primary mr-2" />
                        <input asp-action="Details" asp-route-id="@Model.Id" asp-route-status="@Challenge.ChallengeStatus.Rejected" type="submit" value="Reject" class="btn btn-danger" />
                        break;
                    case Challenge.ChallengeStatus.Accepted:
                        <a asp-area="User" asp-controller="WorkoutResults" asp-action="Create" asp-route-id="@Model.WorkoutId" asp-route-challenge="@Model.Id" class="btn btn-secondary">Record Results</a>
                        break;
                    case Challenge.ChallengeStatus.CompletedByChallenger:
                        <a asp-area="User" asp-controller="WorkoutResults" asp-action="Create" asp-route-id="@Model.WorkoutId" asp-route-challenge="@Model.Id" class="btn btn-secondary">Record Results</a>
                        break;
                }
            }
            else
            {
                switch (Model.ChallengeProgress)
                {
                    case Challenge.ChallengeStatus.Accepted:
                        <a asp-area="User" asp-controller="WorkoutResults" asp-action="Create" asp-route-id="@Model.WorkoutId" asp-route-challenge="@Model.Id" class="btn btn-secondary">Record Results</a>
                        break;
                    case Challenge.ChallengeStatus.CompletedByContender:
                        <a asp-area="User" asp-controller="WorkoutResults" asp-action="Create" asp-route-id="@Model.WorkoutId" asp-route-challenge="@Model.Id" class="btn btn-secondary">Record Results</a>
                        break;
                }
            }
        </form>
    </div>
</div>

<div class="mb-3">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChallengeProgress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChallengeProgress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Challenger)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Challenger.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contender.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Workout)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Workout.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChallengerResult)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChallengerResult.Score)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContenderResult)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContenderResult.Score)
        </dd>

    </dl>
</div>

<div class="btn-toolbar mb-2 mb-md-0">
    <a class="btn btn-secondary mr-2" asp-area="User" asp-controller="Challenges" asp-action="Index">Cancel</a>
</div>

SWENG894/Areas/User/Views/Challenges/Index.cshtml
@model SWENG894.Utility.PaginatedList<SWENG894.Models.Challenge>

<h4>My Challenges</h4>

<form asp-action="Index" method="get">
    <div class="btn-group mb-2" role="group">

        <div class="input-group mb-3">
            <div class="btn-group btn-group-toggle mr-2" role="group">
                <a asp-action="Index" asp-route-list="" type="button" class="btn btn-outline-secondary" id="active">Active</a>
                <a asp-action="Index" asp-route-list="old" type="button" class="btn btn-outline-secondary" id="old">Old</a>
            </div>
            <input type="text" class="form-control" placeholder="Search" aria-label="Search" name="search" aria-describedby="button-find" value="@ViewBag.CurrentFilter">
            <input type="hidden" name="list" value="@ViewBag.CurrentList" />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-find">Search</button>
            </div>
        </div>
    </div>
    <a class="btn btn-primary float-right" id="button-find" asp-action="Create">New Challenge</a>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Status
            </th>
            <th>
                Challenger
            </th>
            <th>
                Contender
            </th>
            <th>
                Options
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChallengeProgress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Challenger.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contender.FullName)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle" tool-tip-toggle="tooltip" data-original-title="Challenge Details"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sort="@ViewBag.CurrentSort"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-search="@ViewBag.CurrentFilter"
   asp-route-box="@ViewBag.List"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sort="@ViewBag.CurrentSort"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-search="@ViewBag.CurrentFilter"
   asp-route-box="@ViewBag.List"
   class="btn btn-default @nextDisabled">
    Next
</a>

@section Scripts {
    <script>
        var tab = GetParameterByName("list");
        if (tab != null && tab != "") {
            $("#old").button('toggle');
        } else {
            $("#active").button('toggle');
        }
    </script>
}